@startuml "refund-requests-api-flow"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Install UPM package from Asset Store
actor Consumer as Consumer

UPM -> UPM_Registry : GET /<name>
UPM_Registry -> UPM : return package metadata + url

UPM -> UPM_Registry : GET /-/api/download-info/<name>/<version>
UPM_Registry -> ASv1 : GET /package/packman_download?kharma_user_id=<userId>&name=<name>&version=<version>
ASv1 -> UPM_Registry : return decryption key
UPM_Registry -> UPM: return decryption key

UPM -> UPM_Registry: GET package url
UPM_Registry -> UPM: download tarball
UPM -> UPM : decrypt the downloaded tarball 
UPM -> UPM : move tarball to the UPM global cache

@enduml