@startuml "refund-requests-api-flow"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Publish or Update UPM package

== Publish New Package==


Editor -> UPM_Registry : GET /metadata
UPM_Registry -> ASv1 : GET /packman/metadata
ASv1 -> UPM_Registry : return PublisherMeta + PulbisherPackages
UPM_Registry -> Editor: return PublisherMeta + PulbisherPackages

Editor -> UPM_Registry : GET /terms/check
UPM_Registry -> ASv2 : GET /external-api/upm/terms/<userId>/check
ASv2 ->  UPM_Registry: data
UPM_Registry -> Editor : data

Editor -> UPM_Registry : GET /legacy-package-download-info
UPM_Registry -> ASv1 : GET /package/download/<packageId>
ASv2 ->  UPM_Registry: data
UPM_Registry -> Editor : data

note left 
    1. check if belongs to publisher 
    2. check if unique 
end note

Editor -> UPM_Registry : POST /upload
UPM_Registry -> GCS : Upload upm package file
UPM_Registry -> ASv1 : POST /packman/upload - Save asset store metadata
UPM_Registry -> Editor: retrun 200 ok

== Update ==




@enduml
